# Generated by Django 2.1.13 on 2019-11-08 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('sharing_credit', models.FloatField()),
                ('using_credit', models.FloatField()),
                ('rate', models.FloatField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryMachine',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_id', models.IntegerField(default=0)),
                ('machine_type', models.CharField(blank=True, default='GPU', max_length=40)),
                ('core_num', models.IntegerField(blank=True, default=1)),
                ('memory_size', models.FloatField(null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(blank=True, default='', max_length=64)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.BigIntegerField(default=0)),
                ('end_time', models.BigIntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('used_credits', models.FloatField(default=0)),
                ('libs', models.CharField(blank=True, default='', max_length=1024)),
                ('archives', models.CharField(blank=True, default='', max_length=1024)),
                ('app_params', models.CharField(blank=True, default='', max_length=1024)),
                ('entry_file', models.CharField(default='', max_length=1024)),
                ('status', models.CharField(blank=True, default='Available', max_length=40)),
                ('spark_id', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_port', models.CharField(blank=True, default='8000', max_length=32)),
                ('hostname', models.CharField(default='', max_length=50)),
                ('machine_type', models.CharField(blank=True, default='GPU', max_length=40)),
                ('ip_address', models.CharField(blank=True, default='127.0.0.1', max_length=64)),
                ('core_num', models.IntegerField(blank=True, default=1)),
                ('memory_size', models.FloatField(null=True)),
                ('start_time', models.DateTimeField()),
                ('time_period', models.IntegerField(null=True)),
                ('available', models.BooleanField(default=False)),
                ('public_key', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(default='', max_length=200)),
                ('credit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.Credit')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historymachine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
