# Generated by Django 2.1.13 on 2019-10-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='root_path',
        ),
        migrations.AddField(
            model_name='job',
            name='app_params',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='job',
            name='archives',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='job',
            name='entry_file',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='job',
            name='libs',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
