# Generated by Django 2.1.13 on 2019-11-08 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 8, 5, 18, 54, 533686)),
        ),
    ]
