# Generated by Django 2.1.13 on 2019-10-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20191012_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='public_key',
            field=models.FileField(default=12, upload_to=''),
            preserve_default=False,
        ),
    ]
