# Generated by Django 2.1.13 on 2019-10-23 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20191023_0341'),
        ('services', '0002_auto_20191012_1933'),
    ]

    operations = [
    ]
