# Generated by Django 2.1.13 on 2019-10-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_merge_20191023_0556'),
        ('services', '0003_merge_20191023_0451'),
    ]

    operations = [
    ]
