# Generated by Django 2.1.13 on 2019-10-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_merge_20191023_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='spark_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
