# Generated by Django 2.1.13 on 2019-10-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_machine_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='hostname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
