# Generated by Django 2.1.14 on 2019-11-20 04:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20191108_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(blank=True, default='1', max_length=40),
        ),
        migrations.AlterField(
            model_name='machine',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 4, 35, 26, 811151, tzinfo=utc)),
        ),
    ]
