# Generated by Django 2.1.13 on 2019-10-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_machine_hostname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='service_port',
        ),
    ]
