# Generated by Django 2.1.14 on 2019-11-20 06:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20191120_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='premium_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='premium_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 6, 30, 50, 617681, tzinfo=utc)),
        ),
    ]
