# Generated by Django 2.1.13 on 2019-10-28 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_job_spark_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='end_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='job_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='start_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='used_credits',
            field=models.IntegerField(default=0),
        ),
    ]
