# Generated by Django 2.1.13 on 2019-10-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20191028_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='core_num',
        ),
        migrations.RemoveField(
            model_name='job',
            name='machine_type',
        ),
        migrations.AddField(
            model_name='job',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
