# Generated by Django 2.1.14 on 2019-11-30 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20191120_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
