# Generated by Django 2.1.13 on 2019-10-29 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_merge_20191023_0623'),
        ('services', '0006_auto_20191028_1857'),
    ]

    operations = [
    ]
