# Generated by Django 2.1.13 on 2019-10-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_merge_20191029_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='used_credits',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_type',
            field=models.CharField(blank=True, default='1', max_length=40),
        ),
    ]
