# Generated by Django 2.1.13 on 2019-10-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20191029_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='sharing_credit',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='credit',
            name='using_credit',
            field=models.FloatField(),
        ),
    ]
