# Generated by Django 2.1.13 on 2019-10-29 21:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0009_auto_20191029_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryMachine',
            fields=[
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_id', models.IntegerField(default=0)),
                ('machine_type', models.CharField(blank=True, default='GPU', max_length=40)),
                ('core_num', models.IntegerField(blank=True, default=1)),
                ('memory_size', models.FloatField(null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 21, 9, 42, 338074)),
        ),
    ]
