# Generated by Django 2.1.13 on 2019-10-29 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20191029_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 23, 36, 10, 702397)),
        ),
    ]
